# Generated by Django 5.1.7 on 2025-06-06 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
        ('salario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarioPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.contato')),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salario.salario')),
            ],
            options={
                'unique_together': {('pessoa', 'salario')},
            },
        ),
    ]
