# Generated by Django 5.1.7 on 2025-06-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('salario', '0001_initial'),
        ('salario_pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='salarios',
            field=models.ManyToManyField(related_name='pessoas', through='salario_pessoa.SalarioPessoa', to='salario.salario'),
        ),
    ]
