# Generated by Django 5.1.7 on 2025-07-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_contato_salarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='data_envio',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='mensagem',
        ),
        migrations.AddField(
            model_name='contato',
            name='cpf',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='idade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
