# Generated by Django 5.1.7 on 2025-07-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_remove_contato_data_envio_remove_contato_mensagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
