# Generated by Django 5.1.7 on 2025-07-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_alter_contato_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
